### ISSUE TITLE
node-zookeeper won't build on v0.12.x

### ISSUE THREAD

**Issue by T1B0** [yfinkelstein/node-zookeeper#117]
npm gives : 
```
λ npm install             
npm WARN package.json zookeeper@3.4.6-8 No license field.

> zookeeper@3.4.6-8 install /media/data1/code/node-zookeeper
> node-gyp rebuild

make: Entering directory '/media/data1/code/node-zookeeper/build'
  ACTION binding_gyp_libzk_target_build_zk_client_lib .
scripts/build.sh: 11: cd: can't cd to /media/data1/code/node-zookeeper/deps/zookeeper/src/c
Unable to build zookeeper library
libzk.target.mk:13: recipe for target '.' failed
make: *** [.] Error 1
make: Leaving directory '/media/data1/code/node-zookeeper/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/media/data1/inst/node-v0.12.7/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "node" "/media/data1/inst/node-v0.12.7/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /media/data1/code/node-zookeeper
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 

npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "node" "/media/data1/inst/nodejs/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.14.8
npm ERR! code ELIFECYCLE
npm ERR! zookeeper@3.4.6-8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zookeeper@3.4.6-8 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the zookeeper package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls zookeeper
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /media/data1/code/node-zookeeper/npm-debug.log
```
while it works totally fine with node v0.10.40

**Comment by mdlavin** [comment]
If you are trying to run `npm install` in a cloned repo of the project, you first need to run `npm run-script prepublish` and then `npm install`
