### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by pc-jedi** [yfinkelstein/node-zookeeper#120]
I'm getting the following issue then runing `npm install` with windows

```
$ npm install --msvs_version=2015

> zookeeper@3.4.6-8 install C:\Users\xxxx\Projects\hub\node_modules\zookeeper
> node-gyp rebuild


C:\Users\d060216\Projects\hub\node_modules\zookeeper>if not defined npm_config_node_gyp (node "C:\Users\xxxx\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): warning MSB8017: A circular dependency has been detected while executing custom build commands for item ".". This may cause incremental build to work incorrectly. [C:\Users\xxxx\Projects\hub\node_modules\zookeeper\build\libzk.vcxproj]
  build_zk_client_lib
  ..\scripts\build.sh: line 3: ./scripts/env.sh: No such file or directory
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1. [C:\Users\xxxx\Projects\hub\node_modules\zookeeper\build\libzk.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\xxxx\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\xxxx\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\d060216\Projects\hub\node_modules\zookeeper
gyp ERR! node -v v5.4.1
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
npm WARN hub@0.0.1 No repository field.
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\xxxx\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--msvs_version=2015"
npm ERR! node v5.4.1
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE
```
Windows 8.1 x64
Visual Studio 2015 community
Windows SDK 8.1

**Comment by mdlavin** [comment]
Windows is currently not a supported platform.  Checkout #78.
