### ISSUE TITLE
How can i install it on windows? It seems impossible,does it?

### ISSUE THREAD

**Issue by caomu** [yfinkelstein/node-zookeeper#126]
i want to install it on windows.but there are some ERR,how can i do next?

```
D:\test\node_modules\zookeeper>if not defined npm_config_node_gyp (node "D:\Prog
ram Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\
bin\node-gyp.js" rebuild )  else (node  rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targ
ets(171,5): warning MSB8017: A circular dependency has been detected while exec
uting custom build commands for item ".". This may cause incremental build to w
ork incorrectly. [D:\test\node_modules\zookeeper\build\libzk.vcxproj]
  build_zk_client_lib
  'sh' 不是内部或外部命令，也不是可运行的程序
  或批处理文件。
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targ
ets(171,5): error MSB6006: “cmd.exe”已退出，代码为 1。 [D:\test\node_modules\z
ookeeper\
build\libzk.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:88:13)
gyp ERR! stack     at ChildProcess.emit (events.js:173:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:201:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\test\node_modules\zookeeper
gyp ERR! node -v v5.2.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
install:underscore        ▌ ╢████████████████████████
install → rollbackFailedO ▌ ╢████████████████████████
install → rollbackFailedO ▀ ╢████████████████████████
runTopLevelLifecycles     ▌ ╢████████████████████████
npm WARN ENOENT ENOENT: no such file or directory, open 'D:\test\package.json'
runTopLevelLifecycles     ▀ ╢█████████████████████████
npm WARN EPACKAGEJSON test No description
runTopLevelLifecycles     ▐ ╢█████████████████████████
npm WARN EPACKAGEJSON test No repository field.
runTopLevelLifecycles     ▄ ╢████████████████████████
npm WARN EPACKAGEJSON test No README data
runTopLevelLifecycles     ▌ ╢████████████████████████
npm WARN EPACKAGEJSON test No license field.
runTopLevelLifecycles     ▀ ╢█████████████████████████
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "zookeeper"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! zookeeper@3.4.6 install: `node-gyp rebuild`
```

**Comment by mdlavin** [comment]
Windows support is currently tracked in #78
