### ISSUE TITLE
Client warns in zookeeper on close

### ISSUE THREAD

**Issue by Stono** [yfinkelstein/node-zookeeper#270]
**Describe the bug**
When calling `.close`, zookeeper logs:

```
2021-04-02 10:48:23,605 [myid:1] - WARN  [NIOWorkerThread-2:NIOServerCnxn@364] - Unexpected exception
EndOfStreamException: Unable to read additional data from client, it probably closed the socket: address = /127.0.0.1:57980, session = 0x10094a0c40d0022
        at org.apache.zookeeper.server.NIOServerCnxn.handleFailedRead(NIOServerCnxn.java:163)
        at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:326)
        at org.apache.zookeeper.server.NIOServerCnxnFactory$IOWorkRequest.doWork(NIOServerCnxnFactory.java:522)
        at org.apache.zookeeper.server.WorkerService$ScheduledWorkRequest.run(WorkerService.java:154)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

Is there a more graceful way to disconnect the client?

**Comment by DavidVujic** [comment]
Hi @Stono , I'm confused about the log message. Is it from the Node.js based client?

**Comment by Stono** [comment]
Apologies I wasn’t very clear!
When calling close on the nodejs client, that’s the error I see on to zookeeper instance.

It’s almost like the connection isn’t closed gracefully.

**Comment by DavidVujic** [comment]
Thank you for clarifying @Stono!

I'll have a look!

**Comment by DavidVujic** [comment]
Great! I will try to reproduce and investigate what could cause the exception on the server.

**Comment by DavidVujic** [comment]
Hi again @Stono !

I am trying to reproduce the server exception locally, by starting a ZooKeeper server in Docker and creating a client that connects and fires the `close` command. But the logs don't output the exception.

I can see the error when I force quit the client running in a terminal window (with Ctrl+C). Then I get the error. Do you have any ideas?

I have googled the error and it seems to be a common problem. I saw one reply about the server configuration, increasing the `tick timeout`. 

Another thing that I'm thinking about it that it could be some version compatibility issues between the server and the client. But I should have seen the error locally then (I think).

**Comment by DavidVujic** [comment]
I just found this issue in the release notes of the Apache ZooKeeper package for v3.7.0:
https://issues.apache.org/jira/browse/ZOOKEEPER-1105

It looks very much like the issue reported here. I think a solution could be to bump the C client version that is used here to build a Node.js AddOn, to the latest one.

**Comment by DavidVujic** [comment]
Related to https://github.com/yfinkelstein/node-zookeeper/issues/240
